/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsIndexRouteImport } from './routes/requests/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as WhoisQueryRouteImport } from './routes/whois/$query'
import { Route as LearnSlugRouteImport } from './routes/learn/$slug'
import { Route as LearnEnIndexRouteImport } from './routes/learn/en/index'
import { Route as LearnEnSlugRouteImport } from './routes/learn/en/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoisQueryRoute = WhoisQueryRouteImport.update({
  id: '/whois/$query',
  path: '/whois/$query',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnEnIndexRoute = LearnEnIndexRouteImport.update({
  id: '/learn/en/',
  path: '/learn/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnEnSlugRoute = LearnEnSlugRouteImport.update({
  id: '/learn/en/$slug',
  path: '/learn/en/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/whois/$query': typeof WhoisQueryRoute
  '/learn/': typeof LearnIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/learn/en/$slug': typeof LearnEnSlugRoute
  '/learn/en/': typeof LearnEnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/whois/$query': typeof WhoisQueryRoute
  '/learn': typeof LearnIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/learn/en/$slug': typeof LearnEnSlugRoute
  '/learn/en': typeof LearnEnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/whois/$query': typeof WhoisQueryRoute
  '/learn/': typeof LearnIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/learn/en/$slug': typeof LearnEnSlugRoute
  '/learn/en/': typeof LearnEnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn/$slug'
    | '/whois/$query'
    | '/learn/'
    | '/requests/'
    | '/learn/en/$slug'
    | '/learn/en/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/learn/$slug'
    | '/whois/$query'
    | '/learn'
    | '/requests'
    | '/learn/en/$slug'
    | '/learn/en'
  id:
    | '__root__'
    | '/'
    | '/learn/$slug'
    | '/whois/$query'
    | '/learn/'
    | '/requests/'
    | '/learn/en/$slug'
    | '/learn/en/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnSlugRoute: typeof LearnSlugRoute
  WhoisQueryRoute: typeof WhoisQueryRoute
  LearnIndexRoute: typeof LearnIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  LearnEnSlugRoute: typeof LearnEnSlugRoute
  LearnEnIndexRoute: typeof LearnEnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whois/$query': {
      id: '/whois/$query'
      path: '/whois/$query'
      fullPath: '/whois/$query'
      preLoaderRoute: typeof WhoisQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/en/': {
      id: '/learn/en/'
      path: '/learn/en'
      fullPath: '/learn/en/'
      preLoaderRoute: typeof LearnEnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/en/$slug': {
      id: '/learn/en/$slug'
      path: '/learn/en/$slug'
      fullPath: '/learn/en/$slug'
      preLoaderRoute: typeof LearnEnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnSlugRoute: LearnSlugRoute,
  WhoisQueryRoute: WhoisQueryRoute,
  LearnIndexRoute: LearnIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  LearnEnSlugRoute: LearnEnSlugRoute,
  LearnEnIndexRoute: LearnEnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
